/**
 * Tournament rule sets (COMP-1). A round picks one; it decides whether AI may
 * run once the round is live and whether recording is possible, and the round
 * shows its reminder. Sources: docs/research/speech-strategy.md §0 (NSDA device
 * guidelines 2023–24, UIL CX manual, OSDA resources, NSDA AI rule).
 */

export type AiPolicy = "allowed" | "prep_only" | "off";
export type RuleSetId = "ai_allowed" | "nsda" | "uil" | "ohio" | "tournament_allows" | "practice";

export interface RuleSet {
  id: RuleSetId;
  label: string;
  /** what the AI may do: allowed = also during the live round; prep_only = before the round only */
  aiPolicy: AiPolicy;
  /** recording opponents: only with everyone's consent, or not at all */
  recording: "consent" | "off";
  reminder: string;
}

export const RULE_SETS: Record<RuleSetId, RuleSet> = {
  ai_allowed: {
    id: "ai_allowed",
    label: "AI allowed (team default)",
    aiPolicy: "allowed",
    recording: "consent",
    reminder:
      "Rules vary by tournament. NSDA's device rules bar competitive help from non-competitors during a round (disqualification), Ohio bans generative AI in rounds, and UIL bans coaching and wireless. Check this tournament's invitation.",
  },
  nsda: {
    id: "nsda",
    label: "NSDA standard",
    aiPolicy: "prep_only",
    recording: "consent",
    reminder:
      "NSDA: competitors may not receive help from non-competitors during the round, including information not generated by the competitors in the round. AI works before the round; typed flow, checklists, timers, and export work throughout. Recording needs written consent.",
  },
  uil: {
    id: "uil",
    label: "UIL (Texas)",
    aiPolicy: "prep_only",
    recording: "off",
    reminder: "UIL: no coaching while a debate is in progress, and wireless must be off. AI works before the round only.",
  },
  ohio: {
    id: "ohio",
    label: "Ohio (OSDA)",
    aiPolicy: "prep_only",
    recording: "off",
    reminder: "OSDA: generative AI may not be used at any time during a debate round. AI works before the round only.",
  },
  tournament_allows: {
    id: "tournament_allows",
    label: "This tournament allows AI",
    aiPolicy: "allowed",
    recording: "consent",
    reminder: "This tournament's rules allow AI assistance during rounds (see the rule text added to this round).",
  },
  practice: {
    id: "practice",
    label: "Practice, scrimmage, or redo",
    aiPolicy: "allowed",
    recording: "consent",
    reminder: "Practice round: every feature is on. Recording still needs the consent of everyone recorded.",
  },
};

export const DEFAULT_RULE_SET: RuleSetId = "ai_allowed";

export function ruleSetOf(settings: { ruleSet?: string } | null | undefined): RuleSet {
  const id = settings?.ruleSet as RuleSetId | undefined;
  return (id && RULE_SETS[id]) || RULE_SETS[DEFAULT_RULE_SET];
}
